"""Finite-state Markov operators, structure, and exact error analysis."""

from sampler_lab.markov.finite_state import (
    CommunicationStructure,
    FiniteStateMarkovChain,
    SpectralSummary,
    validate_transition_matrix,
)
from sampler_lab.markov.kernels import (
    FiniteStateTrajectory,
    sample_categorical,
    simulate_chain,
    transition_step,
)
from sampler_lab.markov.operators import (
    apply_transition,
    as_observable,
    as_probability_vector,
    centered_observable,
    constant_projection,
    covariance,
    expectation,
    operator_duality_residual,
    pushforward_measure,
    variance,
    weighted_inner_product,
)
from sampler_lab.markov.partial_resampling import (
    compose_transitions,
    conditional_component_transition,
    conditional_resampling_transition,
    conjugate_by_permutation,
    mixture_transition,
    normalize_joint_distribution,
)
from sampler_lab.markov.poisson import (
    MartingaleDecomposition,
    PoissonEquationResult,
    asymptotic_variance,
    autocorrelations,
    autocovariances,
    finite_sample_mean_variance,
    integrated_autocorrelation_time,
    lag_covariance,
    poisson_martingale_decomposition,
    solve_poisson_equation,
)

__all__ = [
    "CommunicationStructure",
    "FiniteStateMarkovChain",
    "FiniteStateTrajectory",
    "MartingaleDecomposition",
    "PoissonEquationResult",
    "SpectralSummary",
    "apply_transition",
    "as_observable",
    "as_probability_vector",
    "asymptotic_variance",
    "autocorrelations",
    "autocovariances",
    "centered_observable",
    "compose_transitions",
    "conditional_component_transition",
    "conditional_resampling_transition",
    "conjugate_by_permutation",
    "constant_projection",
    "covariance",
    "expectation",
    "finite_sample_mean_variance",
    "integrated_autocorrelation_time",
    "lag_covariance",
    "mixture_transition",
    "normalize_joint_distribution",
    "operator_duality_residual",
    "poisson_martingale_decomposition",
    "pushforward_measure",
    "sample_categorical",
    "simulate_chain",
    "solve_poisson_equation",
    "transition_step",
    "validate_transition_matrix",
    "variance",
    "weighted_inner_product",
]
