"""Simulation utilities for finite-state transition kernels."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import ArrayLike, NDArray

from sampler_lab.markov.finite_state import FiniteStateMarkovChain
from sampler_lab.markov.operators import as_observable, as_probability_vector

Array = NDArray[np.float64]
IntArray = NDArray[np.int64]


def sample_categorical(probabilities: ArrayLike, rng: np.random.Generator) -> int:
    """Draw one categorical index using a supplied random-number generator."""

    values = as_probability_vector(probabilities)
    cumulative = np.cumsum(values)
    draw = float(rng.random())
    index = int(np.searchsorted(cumulative, draw, side="right"))
    return min(index, values.size - 1)


def transition_step(
    chain: FiniteStateMarkovChain,
    state: int,
    rng: np.random.Generator,
) -> int:
    """Advance a finite-state chain by one transition."""

    if isinstance(state, bool) or not isinstance(state, (int, np.integer)):
        raise TypeError("state must be an integer index")
    state_index = int(state)
    if state_index < 0 or state_index >= chain.n_states:
        raise IndexError("state index out of range")
    return sample_categorical(chain.transition[state_index], rng)


@dataclass(frozen=True, slots=True, init=False)
class FiniteStateTrajectory:
    """Immutable sequence of state indices generated by a finite-state chain."""

    states: IntArray
    n_states: int

    def __init__(self, states: ArrayLike, n_states: int) -> None:
        state_array = np.asarray(states, dtype=np.int64)
        if state_array.ndim != 1 or state_array.size == 0:
            raise ValueError("states must be a nonempty one-dimensional array")
        if isinstance(n_states, bool) or not isinstance(n_states, int) or n_states <= 0:
            raise ValueError("n_states must be a positive integer")
        if np.any(state_array < 0) or np.any(state_array >= n_states):
            raise IndexError("trajectory contains an out-of-range state")
        copied = np.array(state_array, dtype=np.int64, copy=True)
        copied.setflags(write=False)
        object.__setattr__(self, "states", copied)
        object.__setattr__(self, "n_states", n_states)

    @property
    def n_transitions(self) -> int:
        return int(self.states.size - 1)

    def empirical_measure(self, *, discard: int = 0) -> Array:
        """Return normalized state occupancies after an optional prefix discard."""

        if isinstance(discard, bool) or not isinstance(discard, int):
            raise TypeError("discard must be an integer")
        if discard < 0 or discard >= self.states.size:
            raise ValueError("discard must leave at least one state")
        counts = np.bincount(self.states[discard:], minlength=self.n_states)
        return np.asarray(counts / np.sum(counts), dtype=np.float64)

    def observable_values(self, observable: ArrayLike) -> Array:
        """Evaluate a finite-state observable along the trajectory."""

        values = as_observable(observable, n_states=self.n_states)
        return np.asarray(values[self.states], dtype=np.float64)

    def ergodic_average(self, observable: ArrayLike, *, discard: int = 0) -> float:
        """Return a time average after an optional prefix discard."""

        if isinstance(discard, bool) or not isinstance(discard, int):
            raise TypeError("discard must be an integer")
        if discard < 0 or discard >= self.states.size:
            raise ValueError("discard must leave at least one state")
        values = self.observable_values(observable)
        return float(np.mean(values[discard:]))


def simulate_chain(
    chain: FiniteStateMarkovChain,
    rng: np.random.Generator,
    *,
    n_steps: int,
    initial_state: int | None = None,
    initial_distribution: ArrayLike | None = None,
) -> FiniteStateTrajectory:
    """Generate ``n_steps`` transitions and retain the initial state.

    Exactly one of ``initial_state`` and ``initial_distribution`` may be
    supplied. If neither is given, the unique invariant distribution is used.
    """

    if isinstance(n_steps, bool) or not isinstance(n_steps, int):
        raise TypeError("n_steps must be an integer")
    if n_steps < 0:
        raise ValueError("n_steps must be nonnegative")
    if initial_state is not None and initial_distribution is not None:
        raise ValueError("provide at most one initial-state specification")

    if initial_distribution is not None:
        initial = sample_categorical(
            as_probability_vector(initial_distribution, n_states=chain.n_states),
            rng,
        )
    elif initial_state is None:
        initial = sample_categorical(chain.invariant_distribution(), rng)
    else:
        if isinstance(initial_state, bool) or not isinstance(initial_state, (int, np.integer)):
            raise TypeError("initial_state must be an integer index")
        initial = int(initial_state)
        if initial < 0 or initial >= chain.n_states:
            raise IndexError("initial_state is out of range")

    states = np.empty(n_steps + 1, dtype=np.int64)
    states[0] = initial
    for step in range(n_steps):
        states[step + 1] = transition_step(chain, int(states[step]), rng)
    return FiniteStateTrajectory(states, chain.n_states)
